id: 32799764be17482fa39583058773c274
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_300-The_Sutra_on_Reliance_upon_a_Virtuous_Spiritual_Friend-v1
  language: bo
  author: ''
  volume: {}
